### ISSUE TITLE
Deploy sssom api on server

### ISSUE THREAD

**Issue by matentzn** [anitacaron/sssom-api#29]
I send you the login data on slack. Keep it safe.

Here are some instructions on how to open a port:

https://www.cyberciti.biz/faq/how-to-open-firewall-port-on-ubuntu-linux-12-04-14-04-lts/

Here are some instructions on how to setup a website, but I don't think this is needed at all: 
https://www.namecheap.com/support/knowledgebase/article.aspx/10330/2188/how-to-install-linux-apache-mariadb-php-stack-lamp-on-ubuntu-and-host-a-website/

**Comment by anitacaron** [comment]
The address for the API is in the oxo2 slack channel.
