### ISSUE TITLE
Add mapping id to JSON response in `mappings` endpoint

### ISSUE THREAD

**Issue by anitacaron** [anitacaron/sssom-api#34]
Add `mapping_id` in the `others` key object inside Mapping dataclass

**Comment by anitacaron** [comment]
The `other` attribute is a string [(REF)](https://mapping-commons.github.io/sssom/other/), so it's not straightforward to get mapping_id from this attribute. None of the other attributes could fit this request too.

**Comment by matentzn** [comment]
Just provide a nested Json blop, like a dictionary, in the "other" field.

**Comment by anitacaron** [comment]
We need to change the description in the documentation to align with json blop.

> Slot: other
> Pipe separated list of key value pairs for properties not part of the SSSOM spec. Can be used to encode additional provenance data.

**Comment by matentzn** [comment]
You are right! Can you take care of it?

**Comment by anitacaron** [comment]
Nico proposed a new slot for this attribute in the SSSOM model.
