### ISSUE TITLE
Update filter in endpoints

### ISSUE THREAD

**Issue by anitacaron** [anitacaron/sssom-api#58]
- [ ] Change sep to |
~- [ ] Add operator `equals`~

**Comment by matentzn** [comment]
Best Check a bit with Patrick on this; Chris warned me against implementing too much filter logic in the API but I forgot why.

**Comment by anitacaron** [comment]
It's a provisory filter until we have solr.

**Comment by anitacaron** [comment]
I'll only change the sep.
