### ISSUE TITLE
Dynamically generate fastapi endpoint specification from linkml model (SchemaView)

### ISSUE THREAD

**Issue by anitacaron** [anitacaron/sssom-api#6]
My suggestion here is to have a generic filter in this format: `[field]:[operator]:[value]`. The delimiter string is under discussion, and we're open to suggestions.

The list of operators is:

| Operator | Description              |
|----------|--------------------------|
| ge       | greater than or equal to |
| gt       | greater than             |
| le       | less than or equal to    |
| lt       | less than                |
| contains | contains                 |

This list can be extended easily.

The operators are texts to avoid symbols and have more control to translate it to SPARQL query.

Internally, the API verifies the field against the LinkML class.

**Comment by matentzn** [comment]
Look into graphql

min_confidence

seth amigo golr

we need to go more from a use case perspective:

sierra/patrick/kevin/chris meeting to hash out ideas.
